version: '3.8'


services:
  web:
    build: ./testproject
    command:  python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./testproject/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_volume: